export const personas = [
  { id: 1, first_name: "Ashby", email: "apike0@godaddy.com", gender: "Female" },
  {
    id: 2,
    first_name: "Hakeem",
    email: "hrobard1@yellowbook.com",
    gender: "Genderfluid",
  },
  { id: 3, first_name: "Abra", email: "abeslier2@mtv.com", gender: "Bigender" },
  {
    id: 4,
    first_name: "Rodrigo",
    email: "rdrewet3@squarespace.com",
    gender: "Female",
  },
  {
    id: 5,
    first_name: "Lynette",
    email: "lklaes4@ihg.com",
    gender: "Non-binary",
  },
  {
    id: 6,
    first_name: "Zea",
    email: "zstodhart5@sciencedirect.com",
    gender: "Genderqueer",
  },
  {
    id: 7,
    first_name: "Fonsie",
    email: "fbowerbank6@shutterfly.com",
    gender: "Non-binary",
  },
  {
    id: 8,
    first_name: "Steffie",
    email: "srontsch7@hugedomains.com",
    gender: "Genderqueer",
  },
  {
    id: 9,
    first_name: "Anissa",
    email: "apoulton8@last.fm",
    gender: "Non-binary",
  },
  {
    id: 10,
    first_name: "Reynolds",
    email: "ryakutin9@tinypic.com",
    gender: "Non-binary",
  },
  {
    id: 11,
    first_name: "Carol-jean",
    email: "carklea@harvard.edu",
    gender: "Polygender",
  },
  {
    id: 12,
    first_name: "Aloisia",
    email: "amycroftb@parallels.com",
    gender: "Polygender",
  },
  {
    id: 13,
    first_name: "Donall",
    email: "ddarwentc@fotki.com",
    gender: "Female",
  },
  {
    id: 14,
    first_name: "Colette",
    email: "cbruggend@europa.eu",
    gender: "Male",
  },
  {
    id: 15,
    first_name: "Shaw",
    email: "scissene@google.fr",
    gender: "Genderqueer",
  },
  {
    id: 16,
    first_name: "Miriam",
    email: "madrianif@moonfruit.com",
    gender: "Polygender",
  },
  {
    id: 17,
    first_name: "Trefor",
    email: "tbroadnickeg@behance.net",
    gender: "Genderfluid",
  },
  {
    id: 18,
    first_name: "Melinde",
    email: "mkinseyh@ed.gov",
    gender: "Genderqueer",
  },
  {
    id: 19,
    first_name: "Annmarie",
    email: "amarrioni@usda.gov",
    gender: "Bigender",
  },
  {
    id: 20,
    first_name: "Alberto",
    email: "amcgairlj@ning.com",
    gender: "Genderqueer",
  },
];
